/**
 * POST /api/staff/create
 * Create a new staff member (admin only)
 */

const { createAdminClient, verifyAuth, jsonResponse, errorResponse, logActivity } = require('../_config');

module.exports = async (req, res) => {
    if (req.method !== 'POST') {
        return errorResponse(res, 'Method not allowed', 405);
    }

    try {
        const auth = await verifyAuth(req, true);
        if (!auth.valid) {
            return errorResponse(res, auth.error, auth.status);
        }

        const {
            first_name,
            last_name,
            email,
            phone,
            position,
            department,
            employment_type,
            join_date,
            photo_url
        } = req.body;

        // Validate required fields
        if (!first_name || !last_name || !position || !department) {
            return errorResponse(res, 'First name, last name, position, and department are required', 400);
        }

        // Validate email if provided
        if (email) {
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailRegex.test(email)) {
                return errorResponse(res, 'Please provide a valid email address', 400);
            }
        }

        // Validate department
        const validDepartments = [
            'Executive', 'Robotics', 'Artificial Intelligence', 'Finance',
            'Innovation', 'Engineering', 'Operations', 'Marketing', 'Administration'
        ];
        if (!validDepartments.includes(department)) {
            return errorResponse(res, 'Invalid department', 400);
        }

        // Validate employment type
        const validTypes = ['Full Time', 'Part Time', 'Intern', 'Contractor', 'Executive'];
        if (employment_type && !validTypes.includes(employment_type)) {
            return errorResponse(res, 'Invalid employment type', 400);
        }

        const supabase = createAdminClient();

        // Insert staff record (employee_id auto-generated by trigger)
        const { data, error } = await supabase
            .from('staff')
            .insert({
                first_name: first_name.trim(),
                last_name: last_name.trim(),
                email: email ? email.trim().toLowerCase() : null,
                phone: phone ? phone.trim() : null,
                position: position.trim(),
                department,
                employment_type: employment_type || 'Full Time',
                join_date: join_date || new Date().toISOString().split('T')[0],
                photo_url: photo_url || null,
                status: 'active',
                created_by: auth.user.id,
                updated_by: auth.user.id
            })
            .select()
            .single();

        if (error) {
            console.error('Staff creation error:', error);
            return errorResponse(res, 'Failed to create staff member', 500);
        }

        // Log activity
        await logActivity(
            supabase,
            auth.user.id,
            'staff_created',
            'staff',
            data.id,
            `Created staff member: ${data.first_name} ${data.last_name} (${data.employee_id})`
        );

        return jsonResponse(res, {
            success: true,
            message: 'Staff member created successfully',
            data
        });

    } catch (error) {
        console.error('Staff create error:', error);
        return errorResponse(res, 'An unexpected error occurred', 500);
    }
};
